// Code generated by goctl. DO NOT EDIT.
// goctl 1.7.6
// Source: api.proto

package apiuser

import (
	"context"

	"store/app/rpc/api/pb/api"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	AuthReq            = api.AuthReq
	AuthRes            = api.AuthRes
	InitChatLogReq     = api.InitChatLogReq
	InitChatLogRes     = api.InitChatLogRes
	MemberUsersItemReq = api.MemberUsersItemReq
	MemberUsersItemRes = api.MemberUsersItemRes
	MyAllStoreIdReq    = api.MyAllStoreIdReq
	MyAllStoreIdRes    = api.MyAllStoreIdRes
	Response           = api.Response
	StoreChatItem      = api.StoreChatItem
	StoreChatReq       = api.StoreChatReq
	StoreChatRes       = api.StoreChatRes
	StoreInfoReq       = api.StoreInfoReq
	StoreInfoRes       = api.StoreInfoRes
	StoreItem          = api.StoreItem
	StoreListReq       = api.StoreListReq
	StoreListRes       = api.StoreListRes
	StoresChatMap      = api.StoresChatMap
	StoresMap          = api.StoresMap
	UserInfoReq        = api.UserInfoReq
	UserInfoRes        = api.UserInfoRes
	UserItem           = api.UserItem
	UserLoginReq       = api.UserLoginReq
	UserLoginRes       = api.UserLoginRes
	UsersMap           = api.UsersMap

	ApiUser interface {
		Login(ctx context.Context, in *UserLoginReq, opts ...grpc.CallOption) (*UserLoginRes, error)
		Info(ctx context.Context, in *UserInfoReq, opts ...grpc.CallOption) (*UserInfoRes, error)
	}

	defaultApiUser struct {
		cli zrpc.Client
	}
)

func NewApiUser(cli zrpc.Client) ApiUser {
	return &defaultApiUser{
		cli: cli,
	}
}

func (m *defaultApiUser) Login(ctx context.Context, in *UserLoginReq, opts ...grpc.CallOption) (*UserLoginRes, error) {
	client := api.NewApiUserClient(m.cli.Conn())
	return client.Login(ctx, in, opts...)
}

func (m *defaultApiUser) Info(ctx context.Context, in *UserInfoReq, opts ...grpc.CallOption) (*UserInfoRes, error) {
	client := api.NewApiUserClient(m.cli.Conn())
	return client.Info(ctx, in, opts...)
}
