// Code generated by goctl. DO NOT EDIT.
// goctl 1.7.6
// Source: user.proto

package userregister

import (
	"context"

	"store/app/rpc/user/pb/user"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	RegisterReq = user.RegisterReq
	RegisterRes = user.RegisterRes
	Response    = user.Response

	UserRegister interface {
		Register(ctx context.Context, in *RegisterReq, opts ...grpc.CallOption) (*RegisterRes, error)
	}

	defaultUserRegister struct {
		cli zrpc.Client
	}
)

func NewUserRegister(cli zrpc.Client) UserRegister {
	return &defaultUserRegister{
		cli: cli,
	}
}

func (m *defaultUserRegister) Register(ctx context.Context, in *RegisterReq, opts ...grpc.CallOption) (*RegisterRes, error) {
	client := user.NewUserRegisterClient(m.cli.Conn())
	return client.Register(ctx, in, opts...)
}
