// Code generated by goctl. DO NOT EDIT.
// Source: api.proto

package server

import (
	"context"

	"store/app/api/rpc/internal/logic/userservice"
	"store/app/api/rpc/internal/svc"
	"store/app/api/rpc/pb/api"
)

type UserServiceServer struct {
	svcCtx *svc.ServiceContext
	api.UnimplementedUserServiceServer
}

func NewUserServiceServer(svcCtx *svc.ServiceContext) *UserServiceServer {
	return &UserServiceServer{
		svcCtx: svcCtx,
	}
}

func (s *UserServiceServer) Login(ctx context.Context, in *api.UserLoginReq) (*api.UserLoginRes, error) {
	l := userservicelogic.NewLoginLogic(ctx, s.svcCtx)
	return l.Login(in)
}

func (s *UserServiceServer) Info(ctx context.Context, in *api.UserInfoReq) (*api.UserLoginRes, error) {
	l := userservicelogic.NewInfoLogic(ctx, s.svcCtx)
	return l.Info(in)
}
