services:
  store-user:
    container_name: store-user
    image: store-user:${RpcUserVersion}
    restart: always
    ports:
      - "XXXX:8080"
    volumes:
      - ${RpcUserConfigFile}:/app/etc/user.yaml
      - ${LogPath}:/var/log/
    environment:
      TZ: ${TZ}
    networks:
      store:
        ipv4_address: XXX.XXX.XXX.XXX
  store-store:
    container_name: store-store
    image: store-store:${RpcStoreVersion}
    restart: always
    ports:
      - "XXXX:8080"
    volumes:
      - ${RpcStoreConfigFile}:/app/etc/store.yaml
      - ${LogPath}:/var/log/
    environment:
      TZ: ${TZ}
    networks:
      store:
        ipv4_address: XXX.XXX.XXX.XXX
  store-api:
    container_name: store-api
    image: store-api:${RpcApiVersion}
    restart: always
    ports:
      - "XXXX:8080"
    volumes:
      - ${RpcApiConfigFile}:/app/etc/api.yaml
      - ${LogPath}:/var/log/
    environment:
      TZ: ${TZ}
    networks:
      store:
        ipv4_address: XXX.XXX.XXX.XXX
  store-im:
    container_name: store-im
    image: store-im:${RpcImVersion}
    restart: always
    ports:
      - "XXXX:8080"
    volumes:
      - ${RpcImConfigFile}:/app/etc/im.yaml
      - ${LogPath}:/var/log/
    environment:
      TZ: ${TZ}
    networks:
      store:
        ipv4_address: XXX.XXX.XXX.XXX
  store-client:
    container_name: store-client
    image: store-client:${ApiClientVersion}
    restart: always
    depends_on:
      - store-user
      - store-store
      - store-api
      - store-im
    ports:
      - "XXXX:8080"
    volumes:
      - ${ApiClientConfigFile}:/app/etc/client.yaml
      - ${LogPath}:/var/log/
    environment:
      TZ: ${TZ}
    networks:
      store:
        ipv4_address: XXX.XXX.XXX.XXX
  store-ws:
    container_name: store-ws
    image: store-ws:${WsClientVersion}
    restart: always
    depends_on:
      - store-user
      - store-store
      - store-api
      - store-im
    ports:
      - "6999:6999"
    volumes:
      - ${WsClientConfigFile}:/app/etc/ws.yaml
      - ${LogPath}:/var/log/
    environment:
      TZ: ${TZ}
    networks:
      store:
        ipv4_address: XXX.XXX.XXX.XXX
networks:
  store:
    driver: bridge
    ipam:
      config:
        - subnet: XXX.XXX.XXX.0/24