// Code generated by goctl. DO NOT EDIT.
// Source: chat.proto

package socket

import (
	"context"

	"store/app/chat/rpc/pb/chat"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	BroadcastReq = chat.BroadcastReq
	Response     = chat.Response

	Socket interface {
		BroadcastMsg(ctx context.Context, in *BroadcastReq, opts ...grpc.CallOption) (*Response, error)
	}

	defaultSocket struct {
		cli zrpc.Client
	}
)

func NewSocket(cli zrpc.Client) Socket {
	return &defaultSocket{
		cli: cli,
	}
}

func (m *defaultSocket) BroadcastMsg(ctx context.Context, in *BroadcastReq, opts ...grpc.CallOption) (*Response, error) {
	client := chat.NewSocketClient(m.cli.Conn())
	return client.BroadcastMsg(ctx, in, opts...)
}
