// Code generated by goctl. DO NOT EDIT.
// Source: api.proto

package server

import (
	"context"

	"store/app/api/rpc/internal/logic/apiregister"
	"store/app/api/rpc/internal/svc"
	"store/app/api/rpc/pb/api"
)

type ApiRegisterServer struct {
	svcCtx *svc.ServiceContext
	api.UnimplementedApiRegisterServer
}

func NewApiRegisterServer(svcCtx *svc.ServiceContext) *ApiRegisterServer {
	return &ApiRegisterServer{
		svcCtx: svcCtx,
	}
}

func (s *ApiRegisterServer) Register(ctx context.Context, in *api.RegisterReq) (*api.RegisterRes, error) {
	l := apiregisterlogic.NewRegisterLogic(ctx, s.svcCtx)
	return l.Register(in)
}
