// Code generated by goctl. DO NOT EDIT.
// Source: api.proto

package apitoken

import (
	"context"

	"store/app/api/rpc/pb/api"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	AuthReq            = api.AuthReq
	AuthRes            = api.AuthRes
	MemberUsersItemReq = api.MemberUsersItemReq
	MemberUsersItemRes = api.MemberUsersItemRes
	MyAllStoreIdReq    = api.MyAllStoreIdReq
	MyAllStoreIdRes    = api.MyAllStoreIdRes
	Response           = api.Response
	StoreInfoReq       = api.StoreInfoReq
	StoreInfoRes       = api.StoreInfoRes
	StoreItem          = api.StoreItem
	StoreListReq       = api.StoreListReq
	StoreListRes       = api.StoreListRes
	StoresMap          = api.StoresMap
	UserInfoReq        = api.UserInfoReq
	UserInfoRes        = api.UserInfoRes
	UserItem           = api.UserItem
	UserLoginReq       = api.UserLoginReq
	UserLoginRes       = api.UserLoginRes
	UsersMap           = api.UsersMap

	ApiToken interface {
		CheckAuth(ctx context.Context, in *AuthReq, opts ...grpc.CallOption) (*AuthRes, error)
	}

	defaultApiToken struct {
		cli zrpc.Client
	}
)

func NewApiToken(cli zrpc.Client) ApiToken {
	return &defaultApiToken{
		cli: cli,
	}
}

func (m *defaultApiToken) CheckAuth(ctx context.Context, in *AuthReq, opts ...grpc.CallOption) (*AuthRes, error) {
	client := api.NewApiTokenClient(m.cli.Conn())
	return client.CheckAuth(ctx, in, opts...)
}
