// Code generated by goctl. DO NOT EDIT.
package types

type LoginReq struct {
	Mobile   string `json:"mobile,omitempty"`
	Password string `json:"password,omitempty"`
}

type LoginRes struct {
	UserId string `json:"userId"`
	Token  string `json:"token"`
}

type RegisterReq struct {
	Mobile   string `json:"mobile,omitempty"`
	Name     string `json:"name,omitempty"`
	Password string `json:"password,omitempty"`
}

type RegisterRes struct {
	UserId string `json:"userId"`
	Token  string `json:"token"`
}

type StoreInfoReq struct {
	StoreId string `json:"storeId,omitempty"`
}

type StoreInfoRes struct {
	StoreId  string `json:"storeId"`
	Name     string `json:"name"`
	Avatar   string `json:"avatar"`
	Contacts int64  `json:"contacts"`
}

type StoreListRes struct {
	Total   int64       `json:"total"`
	Page    int64       `json:"page"`
	Limit   int64       `json:"limit"`
	Offset  int64       `json:"offset"`
	Current int64       `json:"current"`
	Rows    interface{} `json:"rows"`
}

type StoreUsersReq struct {
	StoreId string `json:"storeId,omitempty"`
	Limit   int64  `json:"limit"`
	Offset  int64  `json:"offset"`
}

type StoreUsersRes struct {
	Total   int64       `json:"total"`
	Page    int64       `json:"page"`
	Limit   int64       `json:"limit"`
	Offset  int64       `json:"offset"`
	Current int64       `json:"current"`
	Rows    interface{} `json:"rows"`
}

type Token struct {
	AccessToken  string `json:"access_token"`
	AccessExpire int64  `json:"access_expire"`
}

type UserInfoReq struct {
	UserId string `json:"userId,omitempty"`
}

type UserInfoRes struct {
	UserId string `json:"userId"`
	Name   string `json:"name"`
	Avatar string `json:"avatar"`
}
