// Code generated by goctl. DO NOT EDIT.
// goctl 1.7.6
// Source: user.proto

package server

import (
	"context"

	"store/app/rpc/user/internal/logic/userregister"
	"store/app/rpc/user/internal/svc"
	"store/app/rpc/user/pb/user"
)

type UserRegisterServer struct {
	svcCtx *svc.ServiceContext
	user.UnimplementedUserRegisterServer
}

func NewUserRegisterServer(svcCtx *svc.ServiceContext) *UserRegisterServer {
	return &UserRegisterServer{
		svcCtx: svcCtx,
	}
}

func (s *UserRegisterServer) Register(ctx context.Context, in *user.RegisterReq) (*user.RegisterRes, error) {
	l := userregisterlogic.NewRegisterLogic(ctx, s.svcCtx)
	return l.Register(in)
}
