// Code generated by goctl. DO NOT EDIT.
// Source: api.proto

package server

import (
	"context"

	"store/app/api/rpc/internal/logic/apitoken"
	"store/app/api/rpc/internal/svc"
	"store/app/api/rpc/pb/api"
)

type ApiTokenServer struct {
	svcCtx *svc.ServiceContext
	api.UnimplementedApiTokenServer
}

func NewApiTokenServer(svcCtx *svc.ServiceContext) *ApiTokenServer {
	return &ApiTokenServer{
		svcCtx: svcCtx,
	}
}

func (s *ApiTokenServer) CheckAuth(ctx context.Context, in *api.AuthReq) (*api.AuthRes, error) {
	l := apitokenlogic.NewCheckAuthLogic(ctx, s.svcCtx)
	return l.CheckAuth(in)
}
