// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"
	"time"

	ws "store/app/chat/socket/internal/handler/ws"
	"store/app/chat/socket/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.XHeaderMiddleware, serverCtx.AuthMiddleware},
			[]rest.Route{
				{
					Method:  http.MethodGet,
					Path:    "/socket",
					Handler: ws.SocketHandler(serverCtx),
				},
			}...,
		),
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
		rest.WithPrefix("/v1/ws"),
		rest.WithTimeout(30000*time.Millisecond),
	)
}
