// Code generated by goctl. DO NOT EDIT.
// Source: api.proto

package server

import (
	"context"

	"store/app/api/rpc/internal/logic/apiuser"
	"store/app/api/rpc/internal/svc"
	"store/app/api/rpc/pb/api"
)

type ApiUserServer struct {
	svcCtx *svc.ServiceContext
	api.UnimplementedApiUserServer
}

func NewApiUserServer(svcCtx *svc.ServiceContext) *ApiUserServer {
	return &ApiUserServer{
		svcCtx: svcCtx,
	}
}

func (s *ApiUserServer) Login(ctx context.Context, in *api.UserLoginReq) (*api.UserLoginRes, error) {
	l := apiuserlogic.NewLoginLogic(ctx, s.svcCtx)
	return l.Login(in)
}

func (s *ApiUserServer) Info(ctx context.Context, in *api.UserInfoReq) (*api.UserInfoRes, error) {
	l := apiuserlogic.NewInfoLogic(ctx, s.svcCtx)
	return l.Info(in)
}
