// Code generated by goctl. DO NOT EDIT.
// goctl 1.7.6

package types

type ConnectReq struct {
	Token string `json:"token,omitempty"`
}

type Response struct {
	ErrMsg  string `json:"errMsg`
	Code    string `json:"code"`
	Message string `json:"message"`
}

type UserInfoRes struct {
	UserId int64  `json:"userId,string"`
	Mobile int64  `json:"mobile,string"`
	Name   string `json:"name"`
	Avatar string `json:"avatar"`
}
