// Code generated by goctl. DO NOT EDIT.
// Source: store.proto

package storeservice

import (
	"context"

	"store/app/store/rpc/pb/store"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	CreateStoreReq     = store.CreateStoreReq
	CreateStoreRes     = store.CreateStoreRes
	JoinStoreMemberReq = store.JoinStoreMemberReq
	JoinStoreMemberRes = store.JoinStoreMemberRes
	Response           = store.Response

	StoreService interface {
		CreateStore(ctx context.Context, in *CreateStoreReq, opts ...grpc.CallOption) (*CreateStoreRes, error)
		JoinStoreMember(ctx context.Context, in *JoinStoreMemberReq, opts ...grpc.CallOption) (*JoinStoreMemberRes, error)
	}

	defaultStoreService struct {
		cli zrpc.Client
	}
)

func NewStoreService(cli zrpc.Client) StoreService {
	return &defaultStoreService{
		cli: cli,
	}
}

func (m *defaultStoreService) CreateStore(ctx context.Context, in *CreateStoreReq, opts ...grpc.CallOption) (*CreateStoreRes, error) {
	client := store.NewStoreServiceClient(m.cli.Conn())
	return client.CreateStore(ctx, in, opts...)
}

func (m *defaultStoreService) JoinStoreMember(ctx context.Context, in *JoinStoreMemberReq, opts ...grpc.CallOption) (*JoinStoreMemberRes, error) {
	client := store.NewStoreServiceClient(m.cli.Conn())
	return client.JoinStoreMember(ctx, in, opts...)
}
