// Code generated by goctl. DO NOT EDIT.
// goctl 1.7.6
// Source: im.proto

package server

import (
	"context"

	"store/app/rpc/im/internal/logic/socket"
	"store/app/rpc/im/internal/svc"
	"store/app/rpc/im/pb/im"
)

type SocketServer struct {
	svcCtx *svc.ServiceContext
	im.UnimplementedSocketServer
}

func NewSocketServer(svcCtx *svc.ServiceContext) *SocketServer {
	return &SocketServer{
		svcCtx: svcCtx,
	}
}

func (s *SocketServer) BroadcastMsg(ctx context.Context, in *im.BroadcastReq) (*im.Response, error) {
	l := socketlogic.NewBroadcastMsgLogic(ctx, s.svcCtx)
	return l.BroadcastMsg(in)
}

func (s *SocketServer) BroadcastBecomeMsg(ctx context.Context, in *im.BroadcastReq) (*im.Response, error) {
	l := socketlogic.NewBroadcastBecomeMsgLogic(ctx, s.svcCtx)
	return l.BroadcastBecomeMsg(in)
}
