// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameChatLog = "chat_log"

// ChatLog 聊天记录表
type ChatLog struct {
	UserId    int64     `gorm:"column:user_id" json:"userId"`       // 用户ID
	StoreId   int64     `gorm:"column:store_id" json:"storeId"`     // 店铺ID
	Message   string    `gorm:"column:message" json:"message"`      // 消息
	Timestamp int64     `gorm:"column:timestamp" json:"timestamp"`  // 记录时间;微秒
	CreatedAt time.Time `gorm:"column:created_at" json:"createdAt"` // 创建时间
	UpdatedAt time.Time `gorm:"column:updated_at" json:"updatedAt"` // 更新时间
}

type ChatLogApi struct {
	UserId    int64  `gorm:"column:user_id" json:"userId,string"`      // 用户ID
	StoreId   int64  `gorm:"column:store_id" json:"storeId,string"`    // 店铺ID
	StoreName string `gorm:"column:store_name" json:"storeName"`       // 店铺
	Message   string `gorm:"column:message" json:"message"`            // 消息
	Timestamp int64  `gorm:"column:timestamp" json:"timestamp,string"` // 记录时间;微秒
	CreatedAt string `gorm:"column:created_at" json:"createdAt"`       // 创建时间
}

type WithChatLog struct {
	StoreId   int64  `gorm:"column:store_id" json:"storeId,string"`    // 店铺ID
	Message   string `gorm:"column:message" json:"message"`            // 消息
	Timestamp int64  `gorm:"column:timestamp" json:"timestamp,string"` // 记录时间;微秒
	CreatedAt string `gorm:"column:created_at" json:"createdAt"`       // 创建时间
}

// TableName ChatLog's table name
func (*ChatLog) TableName() string {
	return TableNameChatLog
}
func ChatLogTableName() string {
	return TableNameChatLog
}
