// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameStoreMember = "store_member"

// StoreMember 店铺会员表
type StoreMember struct {
	Id            uint32    `gorm:"primaryKey;column:id" json:"-"`
	StoreMemberId int64     `gorm:"column:store_member_id" json:"storeMemberId"` // 会员ID
	StoreId       int64     `gorm:"column:store_id" json:"storeId"`              // 店铺ID
	UserId        int64     `gorm:"column:user_id" json:"userId"`                // 用户ID
	CreatedAt     time.Time `gorm:"column:created_at" json:"createdAt"`          // 创建时间
	UpdatedAt     time.Time `gorm:"column:updated_at" json:"updatedAt"`          // 更新时间
}

type MemberUserItem struct {
	StoreMemberId int64    `gorm:"column:store_member_id" json:"storeMemberId,string"` // 会员ID
	StoreId       int64    `gorm:"column:store_id" json:"storeId,string"`              // 店铺ID
	UserId        int64    `gorm:"column:user_id" json:"userId,string"`                // 用户ID
	User          UsersApi `gorm:"foreignkey:user_id;references:user_id"`
}

type MemberChatLog struct {
	StoreName string      `gorm:"column:store_name" json:"storeName"`    // 店铺
	StoreId   int64       `gorm:"column:store_id" json:"storeId,string"` // 店铺ID
	UserId    int64       `gorm:"column:user_id" json:"userId,string"`   // 用户ID
	ChatLog   WithChatLog `gorm:"foreignkey:store_id;references:store_id"`
}

// TableName StoreMember's table name
func (*StoreMember) TableName() string {
	return TableNameStoreMember
}

func StoreMemberTableName() string {
	return TableNameStoreMember
}
