// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameStore = "stores"

const (
	STORE_STATUS_1 int8 = 1
	STORE_STATUS_2 int8 = 2
)

var StoresStatusName = map[int8]string{
	STORE_STATUS_1: "启用",
	STORE_STATUS_2: "禁用",
}

// Store 店铺表
type Stores struct {
	Id        uint32    `gorm:"primaryKey;column:id" json:"-"`
	StoreId   int64     `gorm:"column:store_id" json:"storeId"`        // 店铺ID
	Status    int8      `gorm:"column:status;default:1" json:"status"` // 1-启用、2-禁用
	Name      string    `gorm:"column:name" json:"name"`               // 昵称
	Avatar    string    `gorm:"column:avatar" json:"avatar"`           // 头像
	Desc      string    `gorm:"column:desc" json:"desc"`               // 店铺描述
	CreatedAt time.Time `gorm:"column:created_at" json:"createdAt"`    // 创建时间
	UpdatedAt time.Time `gorm:"column:updated_at" json:"updatedAt"`    // 更新时间
}

type StoresApi struct {
	StoreId int64  `gorm:"column:store_id" json:"storeId,string"` // 店铺ID
	Status  int8   `gorm:"column:status" json:"status"`           // 1-启用、2-禁用
	Name    string `gorm:"column:name" json:"name"`               // 昵称
	Avatar  string `gorm:"column:avatar" json:"avatar"`           // 头像
	Desc    string `gorm:"column:desc" json:"desc"`               // 店铺描述
	// 虚拟字段
	Contacts    int64 `gorm:"-;default:0" json:"contacts"`           // 虚拟字段,店铺会员数
	StoreUserId int64 `gorm:"-;default:0" json:"storeUserId,string"` // 虚拟字段,店铺会员数
	UserId      int64 `gorm:"-;default:0" json:"userId,string"`      // 虚拟字段,店铺会员数
}

type StoresInfoApi struct {
	StoreId int64  `gorm:"column:store_id" json:"storeId,string"` // 店铺ID
	Status  int8   `gorm:"column:status" json:"status"`           // 1-启用、2-禁用
	Name    string `gorm:"column:name" json:"name"`               // 昵称
	Avatar  string `gorm:"column:avatar" json:"avatar"`           // 头像
	Desc    string `gorm:"column:desc" json:"desc"`               // 店铺描述
	// 虚拟字段
	Contacts    int64 `gorm:"contacts;default:0" json:"contacts"`                // 虚拟字段,店铺会员数
	StoreUserId int64 `gorm:"store_user_id;default:0" json:"storeUserId,string"` // 虚拟字段,店铺会员数
	UserId      int64 `gorm:"user_id;default:0" json:"userId,string"`            // 虚拟字段,店铺会员数
}

// TableName Store's table name
func NewStore() *Stores {
	return new(Stores)
}
func (s *Stores) TableName() string {
	return TableNameStore
}
func (s *Stores) StoresTableJoinName() string {
	return "stores as s"
}

func StoresTableName() string {
	return TableNameStore
}
