// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameStoreUser = "store_users"

// StoreUser 店主表
type StoreUsers struct {
	Id          uint32    `gorm:"primaryKey;column:id" json:"-"`
	StoreUserId int64     `gorm:"column:store_user_id" json:"storeUserId"` // 店主ID
	StoreId     int64     `gorm:"column:store_id" json:"storeId"`          // 店铺ID
	UserId      int64     `gorm:"column:user_id" json:"userId"`            // 用户ID
	CreatedAt   time.Time `gorm:"column:created_at" json:"createdAt"`      // 创建时间
	UpdatedAt   time.Time `gorm:"column:updated_at" json:"updatedAt"`      // 更新时间
}
type StoreUsersApi struct {
	StoreUserId int64 `gorm:"column:store_user_id" json:"storeUserId,string"` // 店主ID
	StoreId     int64 `gorm:"column:store_id" json:"storeId,string"`          // 店铺ID
	UserId      int64 `gorm:"column:user_id" json:"userId,string"`            // 用户ID
}

// TableName StoreUser's table name
func (*StoreUsers) TableName() string {
	return TableNameStoreUser
}

func StoreUsersTableName() string {
	return TableNameStoreUser
}
