// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameUser = "users"
const (
	USER_STATUS_1 int8 = 1
	USER_STATUS_2 int8 = 2
)

var UserStatusName = map[int8]string{
	USER_STATUS_1: "启用",
	USER_STATUS_2: "禁用",
}

// User 用户表
type Users struct {
	ID        uint32    `gorm:"primaryKey;column:id" json:"-"`
	UserId    int64     `gorm:"column:user_id" json:"userId"`          // 用户IID
	Status    int8      `gorm:"column:status;default:1" json:"status"` // 1-启用、2-禁用
	Mobile    int64     `gorm:"column:mobile" json:"mobile"`           // 手机号
	Password  string    `gorm:"column:password" json:"password"`       // 密码
	Name      string    `gorm:"column:name" json:"name"`               // 昵称
	Avatar    string    `gorm:"column:avatar" json:"avatar"`           // 头像
	CreatedAt time.Time `gorm:"column:created_at" json:"createdAt"`    // 创建时间
	UpdatedAt time.Time `gorm:"column:updated_at" json:"updatedAt"`    // 更新时间
}
type UsersApi struct {
	UserId int64  `gorm:"column:user_id" json:"userId,string"` // 用户IID
	Status int8   `gorm:"column:status" json:"status"`         // 1-启用、2-禁用
	Mobile int64  `gorm:"column:mobile" json:"mobile,string"`  // 手机号
	Name   string `gorm:"column:name" json:"name"`             // 昵称
	Avatar string `gorm:"column:avatar" json:"avatar"`         // 头像
}

// TableName User's table name
func (*Users) TableName() string {
	return TableNameUser
}

func UserTableName() string {
	return TableNameUser
}
func (usersA *UsersApi) TableName() string {
	return TableNameUser
}
