// Code generated by goctl. DO NOT EDIT.
// Source: user.proto

package server

import (
	"context"

	"store/app/user/rpc/internal/logic/registerservice"
	"store/app/user/rpc/internal/svc"
	"store/app/user/rpc/pb/user"
)

type RegisterServiceServer struct {
	svcCtx *svc.ServiceContext
	user.UnimplementedRegisterServiceServer
}

func NewRegisterServiceServer(svcCtx *svc.ServiceContext) *RegisterServiceServer {
	return &RegisterServiceServer{
		svcCtx: svcCtx,
	}
}

func (s *RegisterServiceServer) Register(ctx context.Context, in *user.RegisterReq) (*user.RegisterRes, error) {
	l := registerservicelogic.NewRegisterLogic(ctx, s.svcCtx)
	return l.Register(in)
}
