// Code generated by goctl. DO NOT EDIT.
// Source: api.proto

package server

import (
	"context"

	"store/app/api/rpc/internal/logic/storeservice"
	"store/app/api/rpc/internal/svc"
	"store/app/api/rpc/pb/api"
)

type StoreServiceServer struct {
	svcCtx *svc.ServiceContext
	api.UnimplementedStoreServiceServer
}

func NewStoreServiceServer(svcCtx *svc.ServiceContext) *StoreServiceServer {
	return &StoreServiceServer{
		svcCtx: svcCtx,
	}
}

func (s *StoreServiceServer) List(ctx context.Context, in *api.StoreListReq) (*api.StoreListRes, error) {
	l := storeservicelogic.NewListLogic(ctx, s.svcCtx)
	return l.List(in)
}

func (s *StoreServiceServer) Info(ctx context.Context, in *api.StoreInfoReq) (*api.StoreInfoRes, error) {
	l := storeservicelogic.NewInfoLogic(ctx, s.svcCtx)
	return l.Info(in)
}

func (s *StoreServiceServer) UserList(ctx context.Context, in *api.StoreUsersReq) (*api.StoreUsersRes, error) {
	l := storeservicelogic.NewUserListLogic(ctx, s.svcCtx)
	return l.UserList(in)
}
